site_name: KGHeartbeat API Documentation

theme:
  name: "material"
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: img/chart.png
  favicon: img/chart.png

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - KGHeartbeat API Docs: index.md
 - reference.md
 - Examples: tutorials.md

repo_url: https://github.com/GabrieleT0/Knowledge-Graph-quality-analysis-API
repo_name: GabrieleT0/KGHearthbeatAPI
